version: '3.8'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    # build:
    image: ghcr.io/smurzz/check-challenge-app-server:1.0.0 # Use an image built from the specified dockerfile
      # dockerfile: Dockerfile
    container_name: app-server
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    links:
      # - mongo-express
      - mongo
    depends_on: 
      # - mongo-express
      - mongo
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
  
  # Frontend Service 
  app-client:
    # build:
    image: ghcr.io/smurzz/check-challenge-app-client:1.0.0 # Use an image built from the specified dockerfile
      # dockerfile: Dockerfile
      # args:
        # REACT_APP_API_BASE_URL: http://localhost:8080
    container_name: app-client
    ports:
      - "3000:3000" 
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend 

# Database Service (MongoDB, Mongo-Express)
  mongo:
    image: ghcr.io/smurzz/mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: check-challenges-db
    volumes:
      - challenge-db:/data/db
    networks:
      - backend
  mongo-express:
    image: ghcr.io/smurzz/mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: "mongodb://admin:password@mongo:27017/"
    networks:
      - backend
# Volumes
volumes:
  challenge-db:
    
# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:  