version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: check-challenges-db
    volumes:
      - challenge-db:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: "mongodb://admin:password@mongo:27017/"
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo-express
      - mongo
    depends_on:
      - mongo-express
      - mongo
volumes:
  challenge-db:
    driver: local
#version: "3.8"
#services:
#  mongo:
#    image: mongo
#    container_name: mongo
#    hostname: mongo
#    restart: unless-stopped
#    ports:
#      - $MONGO_HOST_PORT:27017
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
#      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
#      - MONGO_INITDB_DATABASE=$MONGO_DB
#      - MONGO_DB_USERNAME=$MONGO_DB_USERNAME
#      - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
#    volumes:
#      - $MONGO_DATA_HOST_PATH:/data/db # mongo-data:/data/db
#      # - $MONGO_LOG_HOST_PATH:/var/log/mongodb
#      # - $MONGO_INITDB_SCRIPTS_HOST_PATH:/docker-endpoint-initdb.d/
#    networks:
#      - main-network
#    command: ["--bind_ip", "0.0.0.0"]
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - $MONGO_EXPRESS_HOST_PORT:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_DB_USERNAME
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_DB_PASSWORD
#      - ME_CONFIG_MONGODB_SERVER=mongo
#    networks:
#      - main-network
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile1
#    image: $APP_NAME
#    container_name: $APP_NAME
#    restart: on-failure
#    depends_on:
#      - mongo
#    ports:
#      - $SERVER_HOST_PORT:8080
#    environment:
#      - SERVER_PORT=8080
#      - SPRING_PROFILES_ACTIVE=prod
#      - SPRING_APPLICATION_NAME=$APP_NAME
#      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=$MONGO_DB
#      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=$MONGO_AUTO_INDEX_CREATION
#      - SPRING_DATA_MONGODB_HOST=mongo
#      - SPRING_DATA_MONGODB_PORT=27017
#      - SPRING_DATA_MONGODB_USERNAME=$MONGO_DB_USERNAME
#      - SPRING_DATA_MONGODB_PASSWORD=$MONGO_DB_PASSWORD
#      - SPRING_DATA_MONGODB_DATABASE=$MONGO_DB
#    networks:
#      - main-network
#
#networks:
#  main-network:
#    external:
#      name: $NETWORK_NAME