logging:
   level:
      org:
         springframework:
            data:
               mongodb:
                  core:
                     ReactiveMongoTemplate: DEBUG
            web:
               cors:
                  reactive:
                     DefaultCorsProcessor: DEBUG
server:
   port: 8080
github:
   username: smurzz
jwt:
   secretKey: sUBTuDo0SsnbxJKKRDxlqaddTLjJTu1c
   validityInMs: 3600000
spring:
   config:
      activate:
         on-profile: default
   data:
      mongodb:
         host: localhost
         port: 27017
         database: check-challenges-db
#        username: admin
#        password: password
#        authentication-database: admin
         auto-index-creation: true
---
logging:
   level:
      org:
         springframework:
            data:
               mongodb:
                  core:
                     ReactiveMongoTemplate: DEBUG
            web:
               cors:
                  reactive:
                     DefaultCorsProcessor: DEBUG
github:
   username: smurzz
jwt:
   secretKey: sUBTuDo0SsnbxJKKRDxlqaddTLjJTu1c
   validityInMs: 3600000
spring:
   config:
      activate:
         on-profile: docker
   data:
      mongodb:
         host: mongo
         port: 27018
         database: check-challenges-db
         username: admin
         password: password
         authentication-database: admin
         auto-index-creation: true