name: Build and push Docker image

on:
   push:
      branches:
         - main
      tags:
         - '*'

jobs:
   build-and-push:
      runs-on: ubuntu-latest
      steps:
      -  name: Checkout code
         uses: actions/checkout@v2

      -  name: Build and push app-server image
         uses: docker/build-push-action@v2
         with:
            context: .
            push: true
            tags: ghcr.io/smurzz/check-challenge-app-server:${{ github.sha }}
         env:
            CR_PAT: ${{ secrets.CR_PAT }}

      -  name: Build and push app-client image
         uses: docker/build-push-action@v2
         with:
            context: .
            push: true
            tags: ghcr.io/smurzz/check-challenge-app-client:${{ github.sha }}
         env:
            CR_PAT: ${{ secrets.CR_PAT }}

      -  name: Build and push mongo image
         uses: docker/build-push-action@v2
         with:
            context: .
            push: true
            tags: ghcr.io/smurzz/mongo:${{ github.sha }}
         env:
            CR_PAT: ${{ secrets.CR_PAT }}

      -  name: Build and push mongo-express image
         uses: docker/build-push-action@v2
         with:
            context: .
            push: true
            tags: ghcr.io/smurzz/mongo-express:${{ github.sha }}
         env:
            CR_PAT: ${{ secrets.CR_PAT }}